backend:
  name: git-gateway
  branch: master
media_folder: static/assets/uploads
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }